//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Project_Recipes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingred_Recipe
    {
        public int Recipe_ID { get; set; }
        public int Ingred_ID { get; set; }
        public string Type { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
