//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Project_Recipes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.Ingred_Recipe = new HashSet<Ingred_Recipe>();
        }
    
        public int Ingred_ID { get; set; }
        public string Ingred_Name { get; set; }
    
        public virtual ICollection<Ingred_Recipe> Ingred_Recipe { get; set; }
    }
}
