//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Project_Recipes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal_Type
    {
        public Meal_Type()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int Type_ID { get; set; }
        public string Type_Name { get; set; }
        public int Recipe_FK { get; set; }
        public int Ingred_FK { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
